- name: Deploying basic wordpress
  hosts: all
  become: true
  become_method: sudo
  vars:
    mysql_rootpass: 123cba
    wp_dbname: wp_database
  roles:
    - mysql-install
    - php-install
    - apache2-install
    - wp-install
